Fix: do not bypass read only checks for writing operations
blockstack/stacks-blockchain pull request #2064
Opened 2020-11-16 20:15 UTC by lgalabru

Address https://github.com/blockstack/stacks-blockchain/issues/1852

2020-11-17 19:02 UTC, kantai requested changes
I think if this PR is going to deprecate the implicit tuple syntax, it should also remove the implicit tuple processing code from the other analysis passes (and the runtime). I think this also be opened against `next`.

2020-11-17 23:24 UTC, njordhov commented
> if this PR is going to deprecate the implicit tuple syntax, it should also remove the implicit tuple processing code from the other analysis passes (and the runtime).

PR #1443 eliminated implicit tuple processing code but was never merged thus withdrawn when the code went stale. Consider checking whether parts can be used so you don't have to repeat the work.

2020-11-18 13:59 UTC, lgalabru commented
Apologies if the opening comment was confusing. I initially wrote a patch for the bug that this PR is addressing, then realized that the tuple's implicit syntax would make things harder. 

I was thinking about creating another PR, sunsetting the implicit syntax and then enquire peer reviews on this one.

2020-12-07 19:43 UTC, kantai approved these changes

2020-12-09 14:30 UTC, merged

2024-11-28 00:21 UTC, blockstack-devops commented
This pull request has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.