Stacks 1.0 -> 2.0 automated balance validation
blockstack/stacks-blockchain pull request #2210
Opened 2020-12-23 14:33 UTC by zone117x

Closes https://github.com/blockstack/stacks-blockchain/issues/2128

This is a dockerfile + js script that validates migrated STX balances between Stacks 1.0 and Stacks 2.0. 

The following steps are performed:
1. Checkout and install Stacks 1.0.
2. Run a Stacks 1.0 fast-sync to get caught up to the latest chain state (as of the latest hosted snapshot).
3. Trigger a fast-sync-dump similar to how it will be triggered from the name threshold.
4. Perform the chainstate export step from the fast-sync-dump.
5. Checkout the Stacks 2.0 source, and copy over the newly exported chainstate.txt, and build.
6. Query the Stacks 1.0 db for 1000 addresses with the highest balances.
7. Spin up both a Stacks 1.0 and Stacks 2.0 node, and validate the address balances match using the account RPC endpoints:
   * Stacks 1.0: `/v1/accounts/{address}/STACKS/balance`
   * Stacks 2.0: `v2/accounts/{address-in-testnet-format}` 

### TODO
* Add a "extra addresses" file that can be manually populated, for example the mapped placeholder addresses should be added to the tests.

### Notes
* Token lockup schedules are not being validated yet. These do not have Stacks 1.0 RPC endpoint, so will likely need to be comparing contents of a Stacks 1.0 sqlite db with Stacks 2.0 lock-up contract calls.

2020-12-23 16:04 UTC, CharlieC3 requested changes
> Docker needs around 60GB of disk space allocated. It can take a long time to finish, upwards of an hour -- every step is resource intensive: compiling, exporting, importing, and validating.
>
> would it be useful to have a custom gh action trigger to run this step? For example we could trigger the action when the "final" automated PR is opened.

If it weren't for the 60GB of space required I would say we can try it on a default GH runner, [but they only have ~14 GB of space available on them.](https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners#supported-runners-and-hardware-resources)

If we really want to use Github Actions for this, we would have more luck creating our own GH runners with enough space on them. But at that point I'm not really sure the extra automation and time required to automate and test this is worth it.

It might be better to just modify our local docker configs to give containers ~100GB of space + ample CPU/memory and run this script locally, then post our results as comments in the PR. Plus, this is only something we'll have to do once, so additional automation on top of what's already automated might not be needed here.

Thoughts?

Only a couple changes noted, but nothing critical! Thank you for this!

2020-12-29 18:46 UTC, zone117x commented
Note: this PR now includes validating token lockup schedules, which also appear to be working as expected.

2020-12-30 14:24 UTC, zone117x commented on migration-verification/run.sh
> +cd "$(dirname "$(realpath "$0")")"
Good catch, fixed!

2020-12-30 14:44 UTC, zone117x commented on migration-verification/run.sh
> +cd "$(dirname "$(realpath "$0")")"
Replaced this script with a more useful README file now that a docker ARG is required.

2020-12-30 14:44 UTC, zone117x commented on migration-verification/Dockerfile
> +RUN git clone --depth 1 --branch v24.2.1.0-xenon https://github.com/blockstack/stacks-blockchain.git /stacks2.0
Done! Added usage instructions to a readme file

2020-12-30 14:50 UTC, CharlieC3 approved these changes
:shipit:

2021-01-05 19:37 UTC, kantai approved these changes
LGTM!

Changes that would be nice to have is a way to parameterize the number of addresses, and rather than ordering by amount, order by `RAND()`

2021-01-07 14:48 UTC, merged

2024-11-26 00:23 UTC, blockstack-devops commented
This pull request has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.